account.default-amount=500
account.transfer-commission=0.02

hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/bank
hibernate.connection.username=postgres
hibernate.connection.password=root
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.current_session_context_class=thread
hibernate.show_sql=true
hibernate.format_sql=false